# https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-heartbeat-options.html
output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elk:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

setup:
  kibana:
    host: "elk:5601"
  ilm.overwrite: true

filebeat.inputs:
- type: log
  enabled: true
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true
  paths:
    - /var/log/russky/*.log
